### ISSUE TITLE
IndexError: boolean index did not match indexed array along dimension 0; dimension is 187500 but corresponding boolean dimension is 562500

### ISSUE THREAD

**Issue by sreesindhu-sabbineni** [xtudbxk/semantic-segmentation-metrics#1]
I am trying to evaluate your DSRG model however whenever I try to predict results on val.txt files I am getting the below error.

```
exception info:multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/ssindhu/winter2020/DSRG-tensorflow/pythonlib/predict.py", line 25, in single_crf_metrics
    m.update(label,crf_pred)
  File "/home/ssindhu/winter2020/DSRG-tensorflow/pythonlib/predict.py", line 120, in update
    self.hist += self._fast_hist(x.flatten(),y.flatten(),self.n_class)
  File "/home/ssindhu/winter2020/DSRG-tensorflow/pythonlib/predict.py", line 116, in _fast_hist
    self.hist = np.bincount( n_class * label_true[mask].astype(int)+label_pred[mask],minlength=n_class**2).reshape(n_class,n_class)
IndexError: boolean index did not match indexed array along dimension 0; dimension is 187500 but corresponding boolean dimension is 562500
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ssindhu/winter2020/DSRG-tensorflow/pythonlib/predict.py", line 84, in metrics_predict_tf_with_crf
    ret = pool.map(single_crf_metrics,params)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
IndexError: boolean index did not match indexed array along dimension 0; dimension is 187500 but corresponding boolean dimension is 562500
```

**Comment by xtudbxk** [comment]
Sorry for the late reply. I just am during a festival holiday, and there is no internet connection before today. This problem seems to arise from the same reason for DSRG project. I just fixed it with the same way and put it to github. You can fetch the neweset version and try again ~

**Comment by sreesindhu-sabbineni** [comment]
Thanks for your reply. I was able to run it successfully. I got 54.71% mIOU. Do you suggest any changes for better mIOU as yours? I used multi scale step as well.

**Comment by xtudbxk** [comment]
Maybe some data augumentation or longer epoches can improve the performance. And using more scales seems also help a little.
